
version: '3'

services:

  configServer:
    container_name: configServer
    image: mongo
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db
    ports:
      - 40001:27017
    volumes:
      - configServer:/data/db

  shardServer:
    container_name: shardServer
    image: mongo
    command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db
    ports:
      - 50001:27017
    volumes:
      - shardServer:/data/db

  shard2Server:
    container_name: shard2Server
    image: mongo
    command: mongod --shardsvr --replSet shard2rs --port 27017 --dbpath /data/db
    ports:
      - 50002:27017
    volumes:
      - shard2Server:/data/db

  shard3Server:
    container_name: shard3Server
    image: mongo
    command: mongod --shardsvr --replSet shard3rs --port 27017 --dbpath /data/db
    ports:
      - 50003:27017
    volumes:
      - shard3Server:/data/db

  shard4Server:
    container_name: shard4Server
    image: mongo
    command: mongod --shardsvr --replSet shard4rs --port 27017 --dbpath /data/db
    ports:
      - 50004:27017
    volumes:
      - shard4Server:/data/db
  
  mongos:
    container_name: mongos
    image: mongo
    command: mongos --configdb cfgrs/192.168.1.29:40001 --bind_ip_all --port 27017
    depends_on:
      - configServer
      - shardServer
      - shard2Server
      - shard3Server
      - shard4Server
    ports:
      - 60000:27017

volumes:
  configServer: {}
  shardServer: {}
  shard2Server: {}
  shard3Server: {}
  shard4Server: {}